version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  exclusions:
    rules:
      - path: internal/client/app.go
        text: "is always nil"
  enable:
    - durationcheck
    - unused
    - errcheck
    - ineffassign
    - makezero
    - misspell
    - nilerr
    # - paralleltest # Reference: https://github.com/kunwardeep/paralleltest/issues/14
    - predeclared
    - staticcheck
    - unconvert
    - unparam
