# Continuous integration handling for Go
name: ci-go

on:
  pull_request:
    paths:
      - .github/workflows/ci-go.yml
      - .golangci.yml
      - go.mod
      - '**.go'

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go mod download
      - uses: golangci/golangci-lint-action@v4

  test:
    name: test (Go v${{ matrix.go-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go test -coverprofile=coverage.out ./...
      - run: go tool cover -html=coverage.out -o coverage.html
      - uses: actions/upload-artifact@v4
        with:
          name: go-${{ matrix.go-version }}-coverage
          path: coverage.html